### ISSUE TITLE
Demosession for Data Center Designer (DCD)

### ISSUE THREAD

**Issue by schwesig** [operate-first/ionos-openshift#1]
Find a common date to demonstrate the Data Center Designer
MUST: @tmicheli @schwesig StefanPusch
COULD: @tux1980

**Comment by schwesig** [comment]
April, 8th
Session in english
to be recorded

- [ ] @tmicheli schedules
- [ ] @durandom invites additional RHs

**Comment by tmicheli** [comment]
I scheduled it for one hour. If we need more time it can be expanded.

**Comment by durandom** [comment]
@tumido please attend this
@goern FYI

**Comment by rbo** [comment]
Please invite me optional too.

**Comment by schwesig** [comment]
Thanks to Stefan for the presentation today!


Terraform on ionos
https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs

ionos cloud api
https://api.ionos.com/docs/cloud/v5/

**Comment by durandom** [comment]
@schwesig can we upload the recording to youtube (op1st channel) and link it to the README in this repo?

**Comment by schwesig** [comment]
@tmicheli can you please share the gmeet recordings, as a participant, I can only view, but not download/upload them.

**Comment by tmicheli** [comment]
@schwesig I gave you editor rights for the recordings

**Comment by schwesig** [comment]
https://youtu.be/SSuEnGU7hJc

**Comment by durandom** [comment]
@tmicheli will add the recording to the README

**Comment by schwesig** [comment]
can someone approve the https://github.com/operate-first/ionos-openshift/pull/5
