### ISSUE TITLE
Problem getting cloud-init to work in IONOS DCD with RHEL8/RHCOS

### ISSUE THREAD

**Issue by orebmann** [operate-first/ionos-openshift#17]
Hi,

we are trying to get the RHEL8 / RH CoreOS Standard qcow2 images to run in IONOS DCD but somehow we did not get cloud-init to run... instead the image always came up with uid/pw prompt but did not take the cloud-init config provided in the IONOS DCD.

A workaround was to baking in the uid/pw into the image using virt-customize, but the target config (providing ssh keys via cloud-init) somehow does not work with IONOS DCD... any ideas?

Thanks a lot in advance for your help.

**Comment by durandom** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/161888/203805180-4f8c0de1-db9e-4d4a-a8e4-139b429ccade.png">

@orebmann did you mark the image as cloud init capable?

**Comment by schwesig** [comment]
Hi Oliver,
thanks for reaching out.
As discussed, feel free to join our Operate First office hours (Mon to Thu, 11am New York UTC-5 / 5pm Europe/​Berlin UTC +1)

**Comment by orebmann** [comment]
Hi we did mark the image as Cloud Init compatible but somehow cloud-init is not triggered.

**Comment by schwesig** [comment]
@durandom I am a little out of ideas. Do you have another "trick" in mind?

**Comment by schwesig** [comment]
/close
what is the current status?
feel free to open again, if needed

**Comment by schwesig** [comment]
@orebmann
